baseURL = "https://chris.bracken.jp/"
languageCode = "en-ca"
defaultContentLanguage = "en-ca"
title = "Chris Bracken"
enableRobotsTXT = true
enableEmoji = true
disableHugoGeneratorInject = true
theme = "mofo"

preserveTaxonomyNames = true
hasCJKLanguage = true
paginate = 5

[author]
  name = "Chris Bracken"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[permalinks]
  post = "/:year/:month/:slug/"

[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "About"
  weight = 20
  identifier = "about"
  url = "/about/"
[[menu.main]]
  name = "Code"
  weight = 30
  identifier = "code"
  url = "/code/"
[[menu.main]]
  name = "Twitter"
  weight = 40
  identifier = "twitter"
  url = "https://twitter.com/cbracken/"

[params]
  since = "2000"                  # Initial site creation, start of copyright.
  dateFormat = "02 January 2006"  # See https://gohugo.io/functions/format/
  ccAttributionName = "Chris Bracken"
  ccAttributionUrl = "https://chris.bracken.jp/about"
  ccLicenseName = "CC BY 4.0"
  ccLicenseUrl = "https://creativecommons.org/licenses/by/4.0"
