baseURL = "https://chris.bracken.jp/"
languageCode = "en-ca"
defaultContentLanguage = "en-ca"
title = "Chris Bracken"
enableRobotsTXT = true
enableEmoji = true
disableHugoGeneratorInject = true
theme = "mofo"

preserveTaxonomyNames = true
hasCJKLanguage = true
paginate = 5

[author]
  name = "Chris Bracken"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[permalinks]
  post = "/:year/:month/:slug/"

[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "About"
  weight = 20
  identifier = "about"
  url = "/about/"
[[menu.main]]
  name = "GitHub"
  weight = 40
  identifier = "github"
  url = "https://github.com/cbracken"
[[menu.main]]
  name = "sr.ht"
  weight = 50
  identifier = "srht"
  url = "https://git.sr.ht/~cbracken"
[[menu.main]]
  name = "Mastodon"
  weight = 60
  identifier = "mastodon"
  url = "https://mastodon.social/web/accounts/851052"

[params]
  since = "2000"                  # Initial site creation, start of copyright.
  dateFormat = "02 January 2006"  # See https://gohugo.io/functions/format/
